### ISSUE TITLE
Develop search system

### ISSUE THREAD

**Issue by Sosokker** [Sosokker/B2D-Ventures#50]

**Comment by Nantawat6510545543** [comment]
there is a bug

**Comment by Nantawat6510545543** [comment]
Image ref:

![Image](https://github.com/user-attachments/assets/7bbf438b-528a-4f91-b86d-67f6d1ad3c0f)

![Image](https://github.com/user-attachments/assets/80f41f61-b4c6-499a-8634-fcd7a6112600)
